id: IB6F1BA4F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:38:39+00:00'
last_modified: '2022-06-08T17:06:48.047426+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03680
  title: གླང་ནག་དགོན་པའི་ལོ་རྒྱུས་མཐོང་གསལ་ཤེལ་གྱི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C4DC:
      image_group_id: I1CZ906
      title: ''
      total_pages: 61
      order: 1
      base_file: C4DC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
