id: P010730
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:53.610225
source_metadata:
  id: bdr:W00KG03680
  title: གླང་ནག་དགོན་པའི་ལོ་རྒྱུས་མཐོང་གསལ་ཤེལ་གྱི་མེ་ལོང
  author: ''
  volumes:
    42cd886f696d4cd9ab5f8b9c41887d59:
      image_group_id: I1CZ906
      title: ''
      volume_number: 1
      total_pages: 61
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
